# Generated by Django 4.0.2 on 2022-02-11 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_cmt_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
